version: "3.9"
services:
  postgres_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5435:5432"
    volumes:
      - data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5053:80"
    depends_on:
      - postgres_db

  update_serves:
    build: 
      context: .
      dockerfile: Dockerfile-update_serves
    restart: always
    depends_on:
      - postgres_db

  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
      - redis

  web:
    build: ./src/nginx
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - api
      
  redis:
    restart: always
    image: redis:6-alpine
    ports:
      - "6381:6379"

volumes:
  data: